theme = 'mycat'

[editor]
line-number = "relative"
color-modes = true
bufferline = 'multiple'
idle-timeout = 5
preview-completion-insert = false
soft-wrap = { enable = true }
popup-border = "all"

[editor.statusline]
center = ["file-type"]

[editor.file-picker]
git-ignore = false
ignore = true
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']
A-k = "half_page_up"
A-j = "half_page_down"
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"
A-w = ":buffer-close"

[keys.insert]
A-k = "half_page_up"
A-j = "half_page_down"
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"

[keys.select]
A-k = "half_page_up"
A-j = "half_page_down"
A-l = "goto_next_buffer"
A-h = "goto_previous_buffer"

[keys.normal.space."."]
h = ":toggle-option lsp.display-inlay-hints"

[keys.normal.g]
w = ["save_selection", "goto_word"]

[keys.normal.space]
o = "file_picker_in_current_buffer_directory"
F = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
